### ISSUE TITLE
PDSA database error

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#91] opened 2016-05-11 20:13 UTC
From: Beth Sommers 
Sent: Wednesday, May 11, 2016 11:42 AM

She is referring to Family Medical Group Northeast.

The intervention tracker didn’t pull over my PDSAs for FMGNE when I inputted visit #4. The coach main page for FMGNE no longer shows the PDSAs either. They are still listed under visit #3, so they didn’t totally disappear. Thoughts on what to do?

Thanks!
Beth

**Comment by seemack** [comment] 2016-05-12 20:00
Caused by a conflict between HIT-only visits and PDSA forwarding.  Being addressed in Issue #87.

**Closed by seemack** 2016-05-12 20:00 UTC
Labels: duplicate
