### ISSUE TITLE
practice export date dropped value not matching what's viewable in the app; it appears to be the date the practice enrolled.  Date Re-entered appears to actually contain the date dropped.

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#85] opened 2016-04-27 20:18 UTC
Elena to send list to Roy

**Comment by rpardee** [comment] 2016-04-28 23:12
Elena sent a list of 25 practices possibly with diverse problems.  Eighteen of these have values in the export columns headed 'Date Dropped', and so I'll focus on those.

The [TL;DR](http://knowyourmeme.com/memes/tldr) is--I don't see any evidence of discrepancy between the app and the export data.  However there is a discrepancy between what the practice list shows is the coach and what the export says is the coach.

It looks to me like the date dropped is not really displayed anywhere in the app.  You enter it when dropping a practice, but that's the only time it appears.  Is that right?

One indication of whether a practice is dropped at all is which action shows in [the practice list view](http://healthy-hearts-northwest.herokuapp.com/practices)--this last column here:

![image](https://cloud.githubusercontent.com/assets/26327/14904000/086da536-0d5a-11e6-829e-f03b0e5c13a9.png)

For the 18 practices with a drop date (incidentally all also have re-entry dates), all show 'Re-enter' as the action.

Two practices (32046 & 12268) have no coach assignment on the practice list view, the rest do have coaches listed (and this is a discrepancy with the export--the export shows none of them as having coaches).

When I pull up the coach practice list view for each coach (for example, [this one](http://healthy-hearts-northwest.herokuapp.com/coach_practices/207/list)) none of these practices are listed at all.  I'm not sure why that is--I expected to see them listed, but grayed out (see #75).

I also pulled up these practices Activities to see what their study enroll (PAL Return) dates were.  All 18 had returned PALs, and none of the dates were the same as the ones listed under 'Date dropped'

Looking at the raw database dump, everything seems to match the export and the app.

So like I say above, I'm not seeing any discrepancies, except for the export showing all 18 as coachless, where coaches are listed for the practices in the practice list.

Unless I misunderstood the complaint, my inclination is to close this as a bad report.

**Comment by rpardee** [comment] 2016-04-29 23:10
From a separate e-mail thread:

From: Kuo, Elena 
Sent: Friday, April 29, 2016 10:29 AM
To: Pardee, Roy; Mack, Christopher
Subject: RE: H2N list of no coach assigned dropped weirdness folks

They don't show as reentered when I look at the clinics through the database so we need to figure out why that error is happening on the back end and have it match what we see in the datbase - or it will keep cropping up as practices drop.  In the database many of these clinics are dropped and not reentered, all the ones that have a note saying they are a SHIP clinic should be dropped completely for example.
________________________________________
From: Pardee, Roy
Sent: Friday, April 29, 2016 9:12 AM
To: Kuo, Elena; Mack, Christopher
Subject: RE: H2N list of no coach assigned dropped weirdness folks
Ah, gotcha.  Can you say whether the content of the drop-out dates are okay?  So all we would need to do is null-out the re-entered dates?
 
I’m lately empowered to make back-end changes to the production system (when not behind GHC firewall) and am working from home, so it’d be very easy for me to make onesy-twosey changes like this.  So the question becomes which practices never re-entered.  You say “many” below, so I’m assuming that means not every practice on the list.
 
What would it take to pin down the list of clinics whose re-entered dates should be squashed?
 
If there are any you know for sure (is it all 3 St. Luke’s on the list?) I’m happy to null out those re-entered dates & drop them from the list.
 
From: Kuo, Elena 
Sent: Friday, April 29, 2016 8:28 AM
To: Pardee, Roy; Mack, Christopher
Subject: RE: H2N list of no coach assigned dropped weirdness folks
 
The problem is that many of these clinics are not actually reentered - they should be dropped.  They should not have a reentry date listed and need to be able to be filtered out of our system.  That St. Lukes I now is an example.
________________________________________
From: Pardee, Roy
Sent: Thursday, April 28, 2016 4:18 PM
To: Kuo, Elena; Mack, Christopher
Subject: RE: H2N list of no coach assigned dropped weirdness folks
Here’s that spreadsheet back w/some extra data attached (esp. the PAL return date).  Like I say on issue 85, I’m not seeing a problem here.

**Comment by rpardee** [comment] 2016-04-29 23:16
I have nulled out the drop_reentry_dt values of the 11 practices mentioned in the above e-mail thread.

I'm wondering if these were not created during the time when issue #77 was active?

Also--correction to my lengthy entry above--these practices do not actually have coaches assigned--I had been mistaking *Recruiter* assignments for Coaches.  So that bit of the export is legitimate too I think.

**Comment by rpardee** [comment] 2016-05-04 20:38
TODO for Elena: test out dropping a practice, doing a practice export and then re-entering the practice, and doing another practice export to confirm that #77 is fixed & the drop_dt and drop_reentry_dt fields are being populated properly.  I'm going to add the 'ready for testing' tag to this as a cue.  Recommend closing this issue once that's satisfied.

Also, in today's db huddle Elena clarified what might be wrong with the balance of the practices in the spreadsheet she sent.  That possible problem is different enough from this that I'm going to create a new issue for it.

**Closed** 2016-05-11 20:23 UTC
Labels: ready for testing
